models/collectives.py
from models.base import Base

class Collective(Base):
    """ User class """
    def __init__(self, *args, **kwargs):
        """ init """
        super().__init__(*args, **kwargs)
        self.name = kwargs.get('name')
        self.handle = kwargs.get('handle')
        self.email = kwargs.get('email')
        self.profile_picture = kwargs.get('profile_picture')
        self.will = kwargs.get('will')
        self.authorities_granted = kwargs.get('authorities_granted')
        self.authorities_recieved = kwargs.get('authorities_recieved')
        self.members = []
        self.internal_props = []
        self.external_props = []
        self.internal_posts = []
        self.public_posts = []
        self.internal_tasks = []
        self.external_tasks = []
        self.internal_dues_amount = ''
        self.internal_dues_frequency = ''
        self.collectives = []
        self.roles_occupied = []
        self.roles_contained = []
        self.invitations_into_collectives = []
        self.my_requests_to_join_collectives = []
        self.requests_to_join_this_collective = []
        self.notifications = []
        self.save_to_db()

api/v1/collectives/__init__.py
from flask import jsonify, request
from models import Collective
from api.v1 import (api_v1,
                    create_one_obj,
                    get_all_or_n_obj,
                    get_all_or_n_obj_by_attr,
                    update_object_attr_by_id,
                    remove_value_from_obj_attr,
                    delete_obj_from_db_with_id)


# POST /collectives - create a new collective
def create_collective():
    """
    route:
        POST /collectives
    1. verify data is present and handle is unique
    2. add the current user (creator of collective) to membership
    3. instantiate the collective
    4. return jsonified response
    Return -> dict: status, message, and new collective
    """
    # verify data is present and handle is unique
    response = create_one_obj('Collective')
    if response.get('status') == 'error':
        return jsonify(response)
    # add the current user (creator of collective) to membership
    if request.current_user:
        response['attributes']['members'] = [request.current_user]
    # instantiate collective
    collective = Collective(**response.get('attributes')).to_dict()
    response['collectives'] = collective
    # return jsonified response
    return jsonify(response)


# GET /collectives - get all collectives
# GET /collectives/n - get some number of collectives
def get_all_or_n_collectives(n=None):
    """
    routes:
        GET /collectives
        GET /collectives/n
    1. get all collectives or
    2. get some number of collectives
    Return -> dict: status, message, and new collective(s)
    """
    return jsonify(get_all_or_n_obj('Collective', n))

# GET /collectives/attr/value
# GET /collectives/attr/value/i
def get_all_or_n_collectives_by_attr(attr, value, i=None):
    """
    routes:
        GET /collectives/attr/value
        GET /collectives/attr/value/i
    1. get all collectives with attr = value or
    2. get some number of collectives with attr = value
    Return -> dict: status, message, and new collective(s)
    """
    return jsonify(get_all_or_n_obj_by_attr('Collective', attr, value, i))

def update_collective_attr_by_id(id, attr, value):
    """
    routes:
        PUT /collectives/id/attr/value
    1. update collective with attr = value or add value into attr if iterable
    Return -> dict: status, message, and updated collective
    """
    return jsonify(update_object_attr_by_id('Collective', id, attr, value))

def remove_value_from_collective_attr(id, attr, value):
    """
    routes:
        DELETE /collectives/id/attr/value
    1. remove value from attr or delete attr value entirely
    Return -> dict: status, message
    """
    return jsonify(remove_value_from_obj_attr('Collective', id, attr, value))

def delete_collective_by_id(id):
    """
    routes:
        DELETE /users/id
    1. delete user
    Return -> dict: status, message
    """
    print('in delete collective')
    return jsonify(delete_obj_from_db_with_id('Collective', id))


@api_v1.route('/collectives', methods=['POST', 'GET', 'DELETE'], strict_slashes=False)
@api_v1.route('/collectives/<n>', methods=['POST', 'GET', 'DELETE'], strict_slashes=False)
@api_v1.route('collectives/<string:attr>/<value>', methods=['GET'], strict_slashes=False)
@api_v1.route('collectives/<id>/<string:attr>/<value>', methods=['PUT', 'DELETE'], strict_slashes=False)
@api_v1.route('collectives/<string:attr>/<value>/<int:i>', methods=['GET'], strict_slashes=False)
def collective_routes(n=None, id=None, attr=None, value=None, i=None):
    if request.method == 'POST':
        return create_collective()
    elif request.method == 'GET':
        # /collectives
        # /collectives/n
        if not attr and not value and not i:
            return get_all_or_n_collectives(n)
        if attr and value:
            return get_all_or_n_collectives_by_attr(attr, value, i)
    elif request.method == 'PUT':
        return update_collective_attr_by_id(id, attr, value)
    elif request.method == 'DELETE':
        if id and attr and value:
            return remove_value_from_collective_attr(id, attr, value)
        collective_id = n
        return delete_collective_by_id(collective_id)

routes/collectives/__init__.py
"""
-----------------------------
  The Point Is to Change It | Routes - collectives
-----------------------------

Routes - collectives Contains:
1. all routes for interacting with/acting as a collectives 
2. calls api endpoints to interact with db

"""

from flask import Blueprint, render_template, redirect, url_for, request
import requests
from helpers import build_url

collectives = Blueprint("collectives", __name__, url_prefix="/collectives")


@collectives.route('/', methods=['GET'], strict_slashes=False)
def index():
    """ browse all collectives  """
    return redirect(url_for('dash.search'))


@collectives.route('/<id>', methods=['GET'], strict_slashes=False)
def profile(id):
    """ view a collective's public page """
    from models.auth import Auth
    current_user = Auth.get_current_user()
    collective = requests.get(build_url('api/collectives/' + id)).json()
    print(collective)
    data = {
        'current_user': current_user,
        'full_view': request.full_view,
        'collective': collective
    }
    return render_template('/dash/public_profile.html', data=data)


@collectives.route('/auth/<id>', methods=['GET'], strict_slashes=False)
def internal_dash(id):
    """ view a collective's internal dashboard  """
    from models.auth import Auth
    current_user = Auth.get_current_user()
    collective = requests.get(build_url('api/collectives/id/' + str(id))).json()
    data = {
        'current_user': current_user,
        'full_view': request.full_view,
        'collective': collective.get('collectives')
    }
    return render_template('/private/collective.html', data=data)


@collectives.route('/auth/<col_id>/roles/<role_id>', methods=['GET'], strict_slashes=False)
def role(col_id, role_id):
    """ role within a collective's internal page """
    return render_template('/dash/role.html')

routes/dashboard/__init__.py
"""
-----------------------------
  The Point Is to Change It | Routes - Dashboard
-----------------------------

Routes - Dashboard Contains:
1. all routes that for the internal dashboard
    * public square
    * notifications
    * search
2. calls api endpoints to interact with db

"""

from flask import Blueprint, render_template, g, request
import requests
from helpers import build_url


dash = Blueprint("dash", __name__, url_prefix="/dash")


@dash.route('/', methods=['GET'], strict_slashes=False)
def public_square():
    """ public square - neither private nor public page """
    from models.auth import Auth
    current_user = Auth.get_current_user()
    print(current_user)
    data = {
        'current_user': current_user,
        'full_view': request.full_view
    }
    return render_template('/dash/public_square.html', data=data)


@dash.route('/notifications', methods=['GET'], strict_slashes=False)
def notifications():
    """ main notifications page for users """
    from models.users import User
    user = User.get_n_by_cls_and_attr('id', request.current_user, 1)
    data = {
        'current_user': user,
        'full_view': request.full_view
    }
    return render_template('/dash/notifications.html', data=data)


@dash.route('/search', methods=['GET', 'POST'], strict_slashes=False)
def search():
    """ main notifications page for users """
    from models.users import User
    from models.collectives import Collective
    from models.auth import Auth
    # if entered search field
    data = {}
    user_input = request.form.get('user_input')
    found_users, found_collectives = [], []
    if user_input:
        # api requests to get users and collectives
        users_by_name_response = requests.get(build_url('api/users/name/' + str(user_input) + '/3'), data=request.form).json()
        users_by_handle_response = requests.get(build_url('api/users/handle/' + str(user_input) + '/3'), data=request.form).json()
        collectives_by_name_response = requests.get(build_url('api/collectives/name/' + str(user_input) + '/3'), data=request.form).json()
        collectives_by_handle_response = requests.get(build_url('api/collectives/handle/' + str(user_input) + '/3'), data=request.form).json()
        print(users_by_name_response)
        # add found collectives to list
        if collectives_by_handle_response.get('status') == 'OK':
            collectives_by_handle = collectives_by_handle_response.get('collectives')
            for collectives in collectives_by_handle:
                found_collectives.append(collectives)
        if collectives_by_name_response.get('status') == 'OK':
            collectives_by_name = collectives_by_name_response.get('collectives')
            for collectives in collectives_by_name:
                found_collectives.append(collectives)
        # add found users to list
        if users_by_handle_response.get('status') == 'OK':
            users_by_handle = users_by_handle_response.get('users')
            for users in users_by_handle:
                found_users.append(users)
        if users_by_name_response.get('status') == 'OK':
            users_by_name = users_by_name_response.get('users')
            for users in users_by_name:
                found_users.append(users)
    # if signed in - SHOULD BE IF AUTHENTICTED
    if request.current_user:
        current_user = Auth.get_current_user()
        if not found_users:
            users_response = requests.get(build_url('api/users/3'), data=request.form).json()
            users = users_response.get('users')
        else:
            users = found_users
        if not found_collectives:
            my_collectives = [Collective.get_n_by_cls_and_attr('id', each, 1) for each in current_user.get('collectives')]
        else:
            my_collectives = found_collectives
        data['current_user'] = current_user
        data['full_view'] = request.full_view
        data['collectives'] = my_collectives
        data['users'] = users
    else:
        if not found_users:
            users_response = requests.get(build_url('api/users/3'), data=request.form).json()
            users = users_response.get('users')
        else:
            users = found_users
        if not found_collectives:
            collectives_response = requests.get(build_url('api/collectives/3'), data=request.form).json()
            collectives = collectives_response.get('collectives')
        else:
            collectives = found_collectives
        data['users'] = users
        data['collectives'] = collectives
        data['full_view'] = request.full_view
        print('IN HERE')
    return render_template('/dash/search.html', data=data)


@dash.route('/create_collective', methods=['GET'], strict_slashes=False)
def create_collective():
    """ page with forms for creating a collective """
    from models.users import User
    user = User.get_n_by_cls_and_attr('id', request.current_user, 1)
    data = {
        'current_user': user,
        'full_view': request.full_view
    }
    return render_template('/dash/create_collective.html', data=data)

routes/users/__init__.py
"""
-----------------------------
  The Point Is to Change It | Routes - users
-----------------------------

Routes - users Contains:
1. all routes for user userss and profile (public and private)
2. calls api endpoints to interact with db

"""

from flask import Blueprint, render_template, request, redirect, url_for

users = Blueprint("users", __name__, url_prefix="/users")




"""
Individual widgets for user
"""


tmp_col = {
    'name': 'Collective Name',
    'handle': '@handle',
    'description': 'Description goes here.'
}
tmp_role = {
    'name': 'Role Name',
    'handle': '@handle',
    'description': 'Description goes here.'
}
tmp_auth = {
    'date': '1-01-2021',
    'action': 'action',
    'granted_to': 'Collective X'
}
tmp_post = {
    'content': 'This is a public post I made.',
    'upvotes': '7',
    'downvotes': '3'
}
tmp_prop = {
    'date': '1-01-2021',
    'description': 'I propose we do this and that.',
    'status': 'pending',
    'pass_condition': '50% + 1',
    'requirement': '5',
    'upvotes': '3',
    'downvotes': '1'
}
tmp_task = {
    'date': '1-01-2021',
    'status': 'incomplete',
    'description': 'Description of the task here.',
    'assigned_by': 'Role Y of Collective X'
}
tmp_dues = {
    'amount': '10',
    'frequency': 'monthly',
    'collective': 'Collective X'
}
context = {
    'task': tmp_task,
    'prop': tmp_prop,
    'post': tmp_post,
    'auth': tmp_auth,
    'role': tmp_role,
    'col': tmp_col,
    'dues': tmp_dues
}


@users.route('/collectives')
def collectives():
    """ view of my collectives widget """
    context['widget'] = 'col'
    return render_template('/dash/widget.html', context=context)


@users.route('/roles')
def roles():
    """ view of my roles widget """
    context['widget'] = 'role'
    return render_template('/dash/widget.html', context=context)


@users.route('/posts')
def posts():
    """ view of my public posts widget """
    context['widget'] = 'post'
    return render_template('/dash/widget.html', context=context)


@users.route('/tasks')
def tasks():
    """ view of my tasks widget """
    context['widget'] = 'task'
    return render_template('/dash/widget.html', context=context)


@users.route('/dues')
def dues():
    """ view of my dues widget """
    context['widget'] = 'dues'
    return render_template('/dash/widget.html', context=context)


@users.route('/proposals')
def proposals():
    """ view of my proposals widget """
    context['widget'] = 'prop'
    return render_template('/dash/widget.html', context=context)


@users.route('/authorities')
def authorities():
    """ view of my collectives widget """
    context['widget'] = 'auth'
    return render_template('/dash/widget.html', context=context)


"""
Other users
"""

@users.route('/', methods=['GET'], strict_slashes=False)
@users.route('/<id>', methods=['GET'], strict_slashes=False)
def profile(id=None):
    """ public user profile """
    from models.users import User
    # not logged in and entered /user
    if not request.current_user and not id:
        return redirect(url_for('landing.index'))
    # not logged in and viewing a user page
    if not request.current_user and id:
        user = User.get_n_by_cls_and_attr('id', id, 1)
        if not user:
            return redirect(url_for('dash.public_square'))
        data = {
            'user': user,
            'full_view': request.full_view
        }
        return render_template('/dash/public_profile.html', data=data)
    # logged in and viewing your account
    if request.current_user:
        if not id or id == request.current_user:
            user = User.get_n_by_cls_and_attr('id', request.current_user, 1)
            data = {
                'current_user': user,
                'full_view': request.full_view
            }
            return render_template('/dash/account.html', data=data)
    # logged in and viewing another user profile
    if request.current_user and id and not id == request.current_user:
        user = User.get_n_by_cls_and_attr('id', id, 1)
        current_user = User.get_n_by_cls_and_attr('id', request.current_user, 1)
        print('IN HERE YO')
        print(request.current_user)
        data = {
            'user': user,
            'current_user': current_user,
            'full_view': request.full_view
        }
        return render_template('/dash/public_profile.html', data=data)
    return redirect(url_for('landing.index'))

templates/dash/collective.html
{% extends 'dash/dash_base.html' %}


<!-- ================================= CONTENT -->
{% block content %}

This is a collective profile

<a href="{{ url_for('collectives.role', id=1) }}">some role in the collective</a>

<a href="{{ url_for('dash.public_square') }}">Public Square</a>


{% endblock %}

templates/dash/dash_base.html
{% extends 'base.html' %}


{% block head %}


<link rel="stylesheet" href="{{ url_for('static', filename='css/dash/dash_base.css') }}">


    


{% endblock %}




{% block main %}


<!-- JINJA SETUP HERE -->


<head>
    <script>
        function public_square_hover(bool) {
            if (bool) {
                document.getElementById('public-square-icon').innerHTML = "PUBLIC SQUARE";
            }
            else {
                document.getElementById('public-square-icon').innerHTML = '<img class="nav-icon" id="parthenon" src="https://storage.googleapis.com/tpitci-static-images/public-sq-wht.svg" alt="Public Square">'
            }
        }

        function account_hover(bool) {
            if (bool) {
                document.getElementById('profile-icon').innerHTML = "PROFILE";
            }
            else {
                document.getElementById('profile-icon').innerHTML = '<img class="nav-icon" src="https://storage.googleapis.com/tpitci-static-images/user.svg" alt="profile icon">'
            }
        }

        function notifications_hover(bool) {
            if (bool) {
                document.getElementById('notifications-icon').innerHTML = "NOTIFICATIONS";
            }
            else {
                document.getElementById('notifications-icon').innerHTML = '<img class="nav-icon" src="https://storage.googleapis.com/tpitci-static-images/noti-rnd.svg" alt="notifications icon">'
            }
        }

        function search_hover(bool) {
            if (bool) {
                document.getElementById('search-icon').innerHTML = "SEARCH";
            }
            else {
                document.getElementById('search-icon').innerHTML = '<img class="nav-icon" src="https://storage.googleapis.com/tpitci-static-images/search.svg" alt="search icon">'
            }
        }


    </script>
</head>

<nav class="navbar">
    <a href="{{ url_for('dash.public_square') }}" id="public-square-icon" onmouseout="public_square_hover(false)" onmouseover="public_square_hover(true)">
        <img class="nav-icon" id="parthenon" src="https://storage.googleapis.com/tpitci-static-images/public-sq-wht.svg" alt="Public Square">
    </a>

{% if current_user %}

    <a href="{{ url_for('users.profile') }}" id="profile-icon" onmouseout="account_hover(false)" onmouseover="account_hover(true)">
        <img class="nav-icon" src="https://storage.googleapis.com/tpitci-static-images/user.svg" alt="profile icon">
    </a>
    <a href="{{ url_for('dash.notifications') }}" id="notifications-icon" onmouseout="notifications_hover(false)" onmouseover="notifications_hover(true)">
        <img class="nav-icon" src="https://storage.googleapis.com/tpitci-static-images/noti-rnd.svg" alt="notifications icon">
    </a>
{% endif %}

    <a href="{{ url_for('dash.search') }}" id="search-icon" onmouseout="search_hover(false)" onmouseover="search_hover(true)">
        <img class="nav-icon" src="https://storage.googleapis.com/tpitci-static-images/search.svg" alt="search icon">
    </a>
</nav>


<div id="content">

{% block content %}

{% endblock %}

</div>



{% endblock %}

{% block footer %}
<a href="https://drive.google.com/drive/folders/1-uKiI99_lV9F5-I9fDDad-xw-sS2Uzv7?usp=sharing">Community Enterprise</a>

{% endblock %}

templates/dash/notifications.html
{% extends 'dash/dash_base.html' %}

{% block title %}
Notifications | 
{% endblock %}

<!-- ================================= CONTENT -->

{% block content %}

<head>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/dash/notifications.css') }}">
    <script>

      document.getElementById('notifications-icon').style.backgroundColor = "var(--color-neutral)";
    
    </script>

</head>


<section id="notifications">

    <div class="card">

        <header class="m-between row-wrap back-light">

                <a href="{{ url_for('collectives.profile', id=2) }}" class="margin-sides-sm und row">
                    <img src="https://storage.googleapis.com/tpitci-static-images/collective.jpg" class="profile-pic">
                    <div class="col">
                        <h4>Group Name</h4>
                        <h4>@handle</h4>
                    </div>
                </a>
        </header>

        <div class="card-body m-center">
                <h3>has invited you to join them.</h3>

        </div>
            
        <footer class="col">
                <div class="btn btn-lg-dark btn-submit">ACCEPT</div>
                <div class="btn btn-lg-light btn-submit">DENIE</div>
        </footer>

    </div>
        

    <div class="card card-body">

        <div class="m-start row-wrap">
            <div class="m-start row">
                Your proposal in
                <a href="{{ url_for('collectives.internal_dash', id=2) }}" class="margin-sides-sm und">
                My Group Name
                </a>
            </div>
            has passed
        </div>

    </div>



    <div class="card card-body">

        <div class="m-start row-wrap back-light">

            <a href="/users/2" class="margin-sides-sm und">
                Username
            </a>
            was nominated for <span class="und">Role Name</span>
            <a href="{{ url_for('collectives.internal_dash', id=2) }}" class="margin-sides-sm und">
            My Group Name
            </a>

        </div>        

    </div>


</section>





{% endblock %}

templates/dash/public_square.html
{% extends 'dash/dash_base.html' %}

{% block title %}
Public Square | 
{% endblock %}

<!-- ================================= CONTENT -->
{% block content %}
<head>

    <script>

      document.getElementById('public-square-icon').style.backgroundColor = "var(--color-neutral)";
    
    </script>

    
</head>

<!-- 
 ================================= CREATE COLLECTIVE BUTTON
<div id="create-collective-container">
    <a href="{{ url_for('dash.create_collective') }}" >
        <button id="create-collective-btn" class="btn-light">Create a Collective</button>
    </a>
</div>
-->




<section>

    <!-- ================================= PUBLIC POST -->
    <form class="card" name="public-post" action="https://thepointistochangeit.com/api/post" method="POST" id="create-public-post-form">
        <div class="card-body textarea-container">
            <textarea name="create-public-post-text" rows="4" cols="1000" maxlength="333">share your achievements</textarea>
        </div>
        <footer>
            <input class="btn btn-lg-dark btn-submit" type="submit" value="SHARE" name="submit-public-post">
        </footer>

    </form>

</section>

<section>

    <div class="card post">

        <header>

          <a href="{{ url_for('users.profile') }}" class="row wide">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/tmp.png" id="post-user-pic">
            <div class="col m-start" >
              <h1>Some Username</h1>
              <h2>@userhandle</h2>
            </div>
          </a>

          <div class="btn-up-or-down-container">
            <div class="btn btn-up btn-sm-light"><div>&#11014;&#xFE0E;</div></div>
            <div class="btn btn-down btn-sm-light"><div>&#11015;&#xFE0E;</div></div>
          </div>

        </header>



      <div class="card-body" id="post-content">

        <div id="post-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
        </div>

      
      </div>



      <footer class="problem">
      
        <div>
            &#9873;&#xFE0E;
        </div>

      </footer>


    </div>



    <div class="card">

        <header>

          <a href="/me" class="row wide">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/tmp2.png" id="post-user-pic">
            <div class="col m-start" >
              <h1>Some Group</h1>
              <h2>@userhandle</h2>
            </div>
          </a>

          <div class="btn-up-or-down-container">
            <a href="/users/me" class="btn btn-up btn-sm-light"><div>&#11014;&#xFE0E;</div></a>
            <div class="btn btn-down btn-sm-light"><div>&#11015;&#xFE0E;</div></div>
          </div>

        </header>



      <div class="card-body" id="post-content">

        <div id="post-text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
            Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris
        </div>

      
      </div>



      <footer class="problem">
      
        <div>
            &#9873;&#xFE0E;
        </div>

      </footer>


    </div>



    <div class="card post">

        <header>

          <a href="/me" class="row wide">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/user-color3.png" id="post-user-pic">
            <div class="col m-start" >
              <h1>Some Username</h1>
              <h2>@userhandle</h2>
            </div>
          </a>

          <div class="btn-up-or-down-container">
            <div class="btn btn-up btn-sm-light"><div>&#11014;&#xFE0E;</div></div>
            <div class="btn btn-down btn-sm-light"><div>&#11015;&#xFE0E;</div></div>
          </div>

        </header>



      <div class="card-body" id="post-content">

        <div id="post-text">
            Lorem ipsum dolor sit amet.
        </div>

      
      </div>



      <footer class="problem">
      
        <div>
            &#9873;&#xFE0E;
        </div>

      </footer>


    </div>





    <div class="card post">

        <header>

          <a href="/me" class="row wide">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/1.png" id="post-user-pic">
            <div class="col m-start" >
              <h1>Some Username</h1>
              <h2>@userhandle</h2>
            </div>
          </a>

          <div class="btn-up-or-down-container">
            <div class="btn btn-up btn-sm-light"><div>&#11014;&#xFE0E;</div></div>
            <div class="btn btn-down btn-sm-light"><div>&#11015;&#xFE0E;</div></div>
          </div>

        </header>



      <div class="card-body" id="post-content">

        <div id="post-text">
            Lorem ipsum dolor sit amet.
        </div>

      
      </div>



      <footer class="problem">
      
        <div>
            &#9873;&#xFE0E;
        </div>

      </footer>


    </div>



    <div class="card post">

        <header>

          <a href="/me" class="row wide">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/2.png" id="post-user-pic">
            <div class="col m-start" >
              <h1>Some Username</h1>
              <h2>@userhandle</h2>
            </div>
          </a>

          <div class="btn-up-or-down-container">
            <div class="btn btn-up btn-sm-light"><div>&#11014;&#xFE0E;</div></div>
            <div class="btn btn-down btn-sm-light"><div>&#11015;&#xFE0E;</div></div>
          </div>

        </header>



      <div class="card-body" id="post-content">

        <div id="post-text">
            Lorem ipsum dolor sit amet.
        </div>

      
      </div>



      <footer class="problem">
      
        <div>
            &#9873;&#xFE0E;
        </div>

      </footer>


    </div>



    <div class="card post">

        <header>

          <a href="/me" class="row wide">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/3.png" id="post-user-pic">
            <div class="col m-start" >
              <h1>Some Username</h1>
              <h2>@userhandle</h2>
            </div>
          </a>

          <div class="btn-up-or-down-container">
            <div class="btn btn-up btn-sm-light"><div>&#11014;&#xFE0E;</div></div>
            <div class="btn btn-down btn-sm-light"><div>&#11015;&#xFE0E;</div></div>
          </div>

        </header>



      <div class="card-body" id="post-content">

        <div id="post-text">
            Lorem ipsum dolor sit amet.
        </div>

      
      </div>



      <footer class="problem">
      
        <div>
            &#9873;&#xFE0E;
        </div>

      </footer>


    </div>





    <div class="card post">

        <header>

          <a href="/me" class="row wide">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/4.png" id="post-user-pic">
            <div class="col m-start" >
              <h1>Some Username</h1>
              <h2>@userhandle</h2>
            </div>
          </a>

          <div class="btn-up-or-down-container">
            <div class="btn btn-up btn-sm-light"><div>&#11014;&#xFE0E;</div></div>
            <div class="btn btn-down btn-sm-light"><div>&#11015;&#xFE0E;</div></div>
          </div>

        </header>



      <div class="card-body" id="post-content">

        <div id="post-text">
            Lorem ipsum dolor sit amet.
        </div>

      
      </div>



      <footer class="problem">
      
        <div>
            &#9873;&#xFE0E;
        </div>

      </footer>


    </div>

</section>
    
    







{% endblock %}