models/base.py
"""
-----------------------------
  The Point Is to Change It | Models - Base
-----------------------------

Models - Base Contains:
1. A base class definition to handle serialization and deserialization

"""

class Base():
    """ Base Model """
    def __init__(self, *args, **kwargs):
        """ init """
        from uuid import uuid4
        for (k, v) in kwargs.items():
            setattr(self, k, v)
        if not 'id' in kwargs.items():
            self.id = str(uuid4())

    def to_dict(self):
        """ return dictionary representation of object """
        return self.__dict__

    """
    GET METHODS
    """
    
    @classmethod
    def get_all(cls):
        """ get all objects of this class """
        from models.storage import storage
        print('in get all')
        return storage.get_all(cls)
    
    @classmethod
    def get_n(cls, n):
        """ get n objects of this class """
        from models.storage import storage
        return storage.get_n(cls, n)
    '''
    @classmethod
    def get_by_cls_and_attr(cls, attr, val):
        from models.storage import storage
        return storage.get_by_cls_and_attr(cls, attr, val)
    '''

    @classmethod
    def get_all_by_cls_and_attr(cls, attr, val):
        """ get all objects where attribute == value """
        from models.storage import storage
        return storage.get_all_by_cls_and_attr(cls, attr, val)
    
    @classmethod
    def get_n_by_cls_and_attr(cls, attr, val, n=None):
        """ get n objects where attribute == value """
        from models.storage import storage
        return storage.get_n_by_cls_and_attr(cls, attr, val, n)

    """
    POST METHODS
    """

    def save_to_db(self):
        from models.storage import storage
        storage.save_obj_to_db(self)

    @classmethod
    def save_to_db_with_dict(cls, obj_dict):
        from models.storage import storage
        storage.save_obj_to_db_with_dict(obj_dict)

    """
    DELETE METHODS
    """

    def delete_from_db(self):
        """ delete this object from db """
        from models.storage import storage
        storage.delete_from_db(self)

    @classmethod
    def delete_from_db_with_id(cls, id):
        """ delete this object from db """
        from models.storage import storage
        storage.delete_from_db_with_id(cls, id)

        
    
    """ REPLACE ALL OF THESE WITH METHODS THAT CORRESPOND TO API METHODS """

    
    @classmethod
    def get_all_or_n_cls(cls, n):
        response = None
        if not n:
            response = cls.get_all()
        else:
            response = cls.get_n(n)
        return response
    
    @classmethod
    def update_attr_by_id(cls, id, attr, value):
        """
        Update an object in the database by attribute and value
        
        USAGE: ------------------------------------------------

        From models.classname import Classname
        Classname.update_attr_by_id(object_id, attr_to_update, new_value)
        """
        from models.storage import storage
        return storage.update_attr_by_id(cls, id, attr, value)
    
    """ DELETES """

    @classmethod
    def remove_attr_value(cls, id, attr, value):
        """
        Remove a value from object in the database
        
        USAGE: ------------------------------------------------

        From models.classname import Classname
        Classname.remove_attr_value(object_id, attr_to_update, new_value)
        """
        from models.storage import storage
        return storage.remove_attr_value(cls, id, attr, value)

routes/authenticate/__init__.py
"""
-----------------------------
  The Point Is to Change It | Routes - authenticate
-----------------------------

Routes - authenticate Contains:
1. all routes for registering, logging in, and logging out
2. calls api endpoints to interact with Auth class and db

"""

from flask import Blueprint, render_template, redirect, url_for, request, jsonify, make_response
import requests
from helpers import build_url

auth = Blueprint("auth", __name__, url_prefix="/auth")


@auth.route('/register', methods=['POST'], strict_slashes=False)
def register():
    """ browse all authenticate  """
    from models.users import User
    new_user = requests.post(build_url('api/users'), data=request.form).json()
    if new_user.get('status') == 'error':
        print('failed to make user')
        return redirect(url_for('landing.index', error=new_user.get('message')))
    response = requests.post(build_url('api/sessions'), data=request.form).json()
    if not response:
        return redirect(url_for('landing.index', data={'error': 'API failure. Please try again later.'}))
    if response.get('status') == 'error':
        return redirect(url_for('landing.index', data={'error': response.get('message')}))
    user = User.get_n_by_cls_and_attr('id', response.get('user').get('id'), 1)
    data = {
        'user': user,
        'current_user': user,
        'full_view': request.full_view,
        'message': "Welcome! Let's get started."
    }
    res = make_response(render_template('/dash/account.html', data=data))
    res.set_cookie('session', response.get('id'))
    return res


@auth.route('/login', methods=['POST'], strict_slashes=False)
def login():
    """ browse all authenticate  """
    from models.users import User
    from models.auth.session import Session
    response = requests.post(build_url('api/sessions'), data=request.form).json()
    if not response:
        return redirect(url_for('landing.index', data={'error': 'API failure. Please try again later.'}))
    if response.get('status') == 'error':
        return redirect(url_for('landing.index', data={'error': response.get('message')}))
    user = response.get('user')
    data = {
        'user': user,
        'current_user': user,
        'full_view': request.full_view
    }
    res = make_response(render_template('/dash/account.html', data=data))
    res.set_cookie('session', response.get('id'))
    return res


@auth.route('/logout', methods=['GET'], strict_slashes=False)
def logout():
    """ delete current user session """

    requests.delete(build_url('api/sessions'), data=request.cookies).json()

    data = {
        'user': None,
        'current_user': None,
        'full_view': request.full_view
    }

    response = make_response(render_template('/public/index.html', data=data))
    return response

routes/users/__init__.py
"""
-----------------------------
  The Point Is to Change It | Routes - users
-----------------------------

Routes - users Contains:
1. all routes for user userss and profile (public and private)
2. calls api endpoints to interact with db

"""

from flask import Blueprint, render_template, request, redirect, url_for

users = Blueprint("users", __name__, url_prefix="/users")




"""
Individual widgets for user
"""


tmp_col = {
    'name': 'Collective Name',
    'handle': '@handle',
    'description': 'Description goes here.'
}
tmp_role = {
    'name': 'Role Name',
    'handle': '@handle',
    'description': 'Description goes here.'
}
tmp_auth = {
    'date': '1-01-2021',
    'action': 'action',
    'granted_to': 'Collective X'
}
tmp_post = {
    'content': 'This is a public post I made.',
    'upvotes': '7',
    'downvotes': '3'
}
tmp_prop = {
    'date': '1-01-2021',
    'description': 'I propose we do this and that.',
    'status': 'pending',
    'pass_condition': '50% + 1',
    'requirement': '5',
    'upvotes': '3',
    'downvotes': '1'
}
tmp_task = {
    'date': '1-01-2021',
    'status': 'incomplete',
    'description': 'Description of the task here.',
    'assigned_by': 'Role Y of Collective X'
}
tmp_dues = {
    'amount': '10',
    'frequency': 'monthly',
    'collective': 'Collective X'
}
context = {
    'task': tmp_task,
    'prop': tmp_prop,
    'post': tmp_post,
    'auth': tmp_auth,
    'role': tmp_role,
    'col': tmp_col,
    'dues': tmp_dues
}


@users.route('/collectives')
def collectives():
    """ view of my collectives widget """
    context['widget'] = 'col'
    return render_template('/dash/widget.html', context=context)


@users.route('/roles')
def roles():
    """ view of my roles widget """
    context['widget'] = 'role'
    return render_template('/dash/widget.html', context=context)


@users.route('/posts')
def posts():
    """ view of my public posts widget """
    context['widget'] = 'post'
    return render_template('/dash/widget.html', context=context)


@users.route('/tasks')
def tasks():
    """ view of my tasks widget """
    context['widget'] = 'task'
    return render_template('/dash/widget.html', context=context)


@users.route('/dues')
def dues():
    """ view of my dues widget """
    context['widget'] = 'dues'
    return render_template('/dash/widget.html', context=context)


@users.route('/proposals')
def proposals():
    """ view of my proposals widget """
    context['widget'] = 'prop'
    return render_template('/dash/widget.html', context=context)


@users.route('/authorities')
def authorities():
    """ view of my collectives widget """
    context['widget'] = 'auth'
    return render_template('/dash/widget.html', context=context)


"""
Other users
"""

@users.route('/', methods=['GET'], strict_slashes=False)
@users.route('/<id>', methods=['GET'], strict_slashes=False)
def profile(id=None):
    """ public user profile """
    from models.users import User
    # not logged in and entered /user
    if not request.current_user and not id:
        return redirect(url_for('landing.index'))
    # not logged in and viewing a user page
    if not request.current_user and id:
        user = User.get_n_by_cls_and_attr('id', id, 1)
        if not user:
            return redirect(url_for('dash.public_square'))
        data = {
            'user': user,
            'full_view': request.full_view
        }
        return render_template('/dash/public_profile.html', data=data)
    # logged in and viewing your account
    if request.current_user:
        if not id or id == request.current_user:
            user = User.get_n_by_cls_and_attr('id', request.current_user, 1)
            data = {
                'current_user': user,
                'full_view': request.full_view
            }
            return render_template('/dash/account.html', data=data)
    # logged in and viewing another user profile
    if request.current_user and id and not id == request.current_user:
        user = User.get_n_by_cls_and_attr('id', id, 1)
        current_user = User.get_n_by_cls_and_attr('id', request.current_user, 1)
        print('IN HERE YO')
        print(request.current_user)
        data = {
            'user': user,
            'current_user': current_user,
            'full_view': request.full_view
        }
        return render_template('/dash/public_profile.html', data=data)
    return redirect(url_for('landing.index'))

templates/base.html
<!doctype html>
<html>

  <!-- ================================= HEAD -->
  <head>
    <title>{% block title %}{% endblock %}The Point Is to Change It</title>
    <meta name="description" content="Build communities that reflect our highest values.">
    <link rel="stylesheet" href="{{ url_for('static', filename='css/base.css') }}">
    <meta name="viewport" content="width=device-width" initial-scale=1.0">
    <meta charset="UTF-8">

    

    {% block head %}
    {% endblock %}

  </head>

  {% if data %}

    {% if data.current_user %}
        {% set current_user = data.current_user %}
    {% endif %}

    {% if data.user %}
        {% set user = data.user %}
    {% endif %}

    {% if data.full_view %}
        {% set full_view = data.full_view %}
    {% endif %}

{% endif %}

  <body>
    <!-- ================================= HEADER -->
    <header class="" color-theme="dark">

        
        <!-- ACTING CAPACITY -->
        {% if current_user %}
        <a href="{{ url_for('users.profile') }}" id="acting-capacity">
          <img class="profile-pic" id="acting-capacity-photo"  src="https://storage.googleapis.com/tpitci-static-images/russ.jpg" alt="acting capacity profile picture">
          <div id="acting-capacity-info">

            <div id="acting-capacity-name">{{ current_user.name }}</div>
            <div id="acting-capacity-handle">@{{ current_user.handle }}</div>
          </div>

        </a>

          <a href="{{ url_for('auth.logout') }}">logout</a> 

        {% else %}
        <a class="logo-container" href="{{ url_for('landing.index') }}">
            <img class="logo" src="https://storage.googleapis.com/tpitci-static-images/logo-dark.png" alt="The Point Is to Change It logo">
        </a>
        {% endif %}

      <!-- MENU BUTTON (INVISIBLE CHECKBOX) -->
        <input type="checkbox" id="menu-checkbox">
        <!-- MENU BUTTON (VISIBLE) -->
        <div id="menu">
          
          <span class="menu-line"></span>
          <span class="menu-line"></span>
          <span class="menu-line"></span>
        </div>


      <!-- MENU CONTENT -->
      <div id="menu-content">
          
      </div>

        <!-- login or logout link -->
        {% if context %}

          {% set login_out = context.login_out %}

          {% if login_out %}
            {{ login_out }}
          {% endif %}

        {% endif %}


      {% block header %}
      {% endblock %}



      




        

    </header>

    <!-- ================================= MAIN -->
    <main color-theme="light">

      {% block main %}
      <body>
          
      </body>
      {% endblock %}

    </main>

    <!-- ================================= FOOTER -->
    <footer color-theme="dark">

        {% block footer %}
        
        {% endblock %}
      
    </footer>

  </body>
</html>