models/collectives.py
from models.base import Base

class Collective(Base):
    """ User class """
    def __init__(self, *args, **kwargs):
        """ init """
        super().__init__(*args, **kwargs)
        self.name = kwargs.get('name')
        self.handle = kwargs.get('handle')
        self.email = kwargs.get('email')
        self.profile_picture = kwargs.get('profile_picture')
        self.will = kwargs.get('will')
        self.authorities_granted = kwargs.get('authorities_granted')
        self.authorities_recieved = kwargs.get('authorities_recieved')
        self.members = []
        self.internal_props = []
        self.external_props = []
        self.internal_posts = []
        self.public_posts = []
        self.internal_tasks = []
        self.external_tasks = []
        self.internal_dues_amount = ''
        self.internal_dues_frequency = ''
        self.collectives = []
        self.roles_occupied = []
        self.roles_contained = []
        self.invitations_into_collectives = []
        self.my_requests_to_join_collectives = []
        self.requests_to_join_this_collective = []
        self.notifications = []
        self.save_to_db()

api/v1/collectives/__init__.py
from flask import jsonify, request
from models import Collective
from api.v1 import (api_v1,
                    create_one_obj,
                    get_all_or_n_obj,
                    get_all_or_n_obj_by_attr,
                    update_object_attr_by_id,
                    remove_value_from_obj_attr,
                    delete_obj_from_db_with_id)


# POST /collectives - create a new collective
def create_collective():
    """
    route:
        POST /collectives
    1. verify data is present and handle is unique
    2. add the current user (creator of collective) to membership
    3. instantiate the collective
    4. return jsonified response
    Return -> dict: status, message, and new collective
    """
    # verify data is present and handle is unique
    response = create_one_obj('Collective')
    if response.get('status') == 'error':
        return jsonify(response)
    # add the current user (creator of collective) to membership
    if request.current_user:
        response['attributes']['members'] = [request.current_user]
    # instantiate collective
    collective = Collective(**response.get('attributes')).to_dict()
    response['collectives'] = collective
    # return jsonified response
    return jsonify(response)


# GET /collectives - get all collectives
# GET /collectives/n - get some number of collectives
def get_all_or_n_collectives(n=None):
    """
    routes:
        GET /collectives
        GET /collectives/n
    1. get all collectives or
    2. get some number of collectives
    Return -> dict: status, message, and new collective(s)
    """
    return jsonify(get_all_or_n_obj('Collective', n))

# GET /collectives/attr/value
# GET /collectives/attr/value/i
def get_all_or_n_collectives_by_attr(attr, value, i=None):
    """
    routes:
        GET /collectives/attr/value
        GET /collectives/attr/value/i
    1. get all collectives with attr = value or
    2. get some number of collectives with attr = value
    Return -> dict: status, message, and new collective(s)
    """
    return jsonify(get_all_or_n_obj_by_attr('Collective', attr, value, i))

def update_collective_attr_by_id(id, attr, value):
    """
    routes:
        PUT /collectives/id/attr/value
    1. update collective with attr = value or add value into attr if iterable
    Return -> dict: status, message, and updated collective
    """
    return jsonify(update_object_attr_by_id('Collective', id, attr, value))

def remove_value_from_collective_attr(id, attr, value):
    """
    routes:
        DELETE /collectives/id/attr/value
    1. remove value from attr or delete attr value entirely
    Return -> dict: status, message
    """
    return jsonify(remove_value_from_obj_attr('Collective', id, attr, value))

def delete_collective_by_id(id):
    """
    routes:
        DELETE /users/id
    1. delete user
    Return -> dict: status, message
    """
    print('in delete collective')
    return jsonify(delete_obj_from_db_with_id('Collective', id))


@api_v1.route('/collectives', methods=['POST', 'GET', 'DELETE'], strict_slashes=False)
@api_v1.route('/collectives/<n>', methods=['POST', 'GET', 'DELETE'], strict_slashes=False)
@api_v1.route('collectives/<string:attr>/<value>', methods=['GET'], strict_slashes=False)
@api_v1.route('collectives/<id>/<string:attr>/<value>', methods=['PUT', 'DELETE'], strict_slashes=False)
@api_v1.route('collectives/<string:attr>/<value>/<int:i>', methods=['GET'], strict_slashes=False)
def collective_routes(n=None, id=None, attr=None, value=None, i=None):
    if request.method == 'POST':
        return create_collective()
    elif request.method == 'GET':
        # /collectives
        # /collectives/n
        if not attr and not value and not i:
            return get_all_or_n_collectives(n)
        if attr and value:
            return get_all_or_n_collectives_by_attr(attr, value, i)
    elif request.method == 'PUT':
        return update_collective_attr_by_id(id, attr, value)
    elif request.method == 'DELETE':
        if id and attr and value:
            return remove_value_from_collective_attr(id, attr, value)
        collective_id = n
        return delete_collective_by_id(collective_id)

routes/collectives/__init__.py
"""
-----------------------------
  The Point Is to Change It | Routes - collectives
-----------------------------

Routes - collectives Contains:
1. all routes for interacting with/acting as a collectives 
2. calls api endpoints to interact with db

"""

from flask import Blueprint, render_template, redirect, url_for, request
import requests
from helpers import build_url

collectives = Blueprint("collectives", __name__, url_prefix="/collectives")


@collectives.route('/', methods=['GET'], strict_slashes=False)
def index():
    """ browse all collectives  """
    return redirect(url_for('dash.search'))


@collectives.route('/<id>', methods=['GET'], strict_slashes=False)
def profile(id):
    """ view a collective's public page """
    from models.auth import Auth
    current_user = Auth.get_current_user()
    collective = requests.get(build_url('api/collectives/' + id)).json()
    print(collective)
    data = {
        'current_user': current_user,
        'full_view': request.full_view,
        'collective': collective
    }
    return render_template('/dash/public_profile.html', data=data)


@collectives.route('/auth/<id>', methods=['GET'], strict_slashes=False)
def internal_dash(id):
    """ view a collective's internal dashboard  """
    from models.auth import Auth
    current_user = Auth.get_current_user()
    collective = requests.get(build_url('api/collectives/id/' + str(id))).json()
    data = {
        'current_user': current_user,
        'full_view': request.full_view,
        'collective': collective.get('collectives')
    }
    return render_template('/private/collective.html', data=data)


@collectives.route('/auth/<col_id>/roles/<role_id>', methods=['GET'], strict_slashes=False)
def role(col_id, role_id):
    """ role within a collective's internal page """
    return render_template('/dash/role.html')

routes/dashboard/__init__.py
"""
-----------------------------
  The Point Is to Change It | Routes - Dashboard
-----------------------------

Routes - Dashboard Contains:
1. all routes that for the internal dashboard
    * public square
    * notifications
    * search
2. calls api endpoints to interact with db

"""

from flask import Blueprint, render_template, g, request
import requests
from helpers import build_url


dash = Blueprint("dash", __name__, url_prefix="/dash")


@dash.route('/', methods=['GET'], strict_slashes=False)
def public_square():
    """ public square - neither private nor public page """
    from models.auth import Auth
    current_user = Auth.get_current_user()
    print(current_user)
    data = {
        'current_user': current_user,
        'full_view': request.full_view
    }
    return render_template('/dash/public_square.html', data=data)


@dash.route('/notifications', methods=['GET'], strict_slashes=False)
def notifications():
    """ main notifications page for users """
    from models.users import User
    user = User.get_n_by_cls_and_attr('id', request.current_user, 1)
    data = {
        'current_user': user,
        'full_view': request.full_view
    }
    return render_template('/dash/notifications.html', data=data)


@dash.route('/search', methods=['GET', 'POST'], strict_slashes=False)
def search():
    """ main notifications page for users """
    from models.users import User
    from models.collectives import Collective
    from models.auth import Auth
    # if entered search field
    data = {}
    user_input = request.form.get('user_input')
    found_users, found_collectives = [], []
    if user_input:
        # api requests to get users and collectives
        users_by_name_response = requests.get(build_url('api/users/name/' + str(user_input) + '/3'), data=request.form).json()
        users_by_handle_response = requests.get(build_url('api/users/handle/' + str(user_input) + '/3'), data=request.form).json()
        collectives_by_name_response = requests.get(build_url('api/collectives/name/' + str(user_input) + '/3'), data=request.form).json()
        collectives_by_handle_response = requests.get(build_url('api/collectives/handle/' + str(user_input) + '/3'), data=request.form).json()
        print(users_by_name_response)
        # add found collectives to list
        if collectives_by_handle_response.get('status') == 'OK':
            collectives_by_handle = collectives_by_handle_response.get('collectives')
            for collectives in collectives_by_handle:
                found_collectives.append(collectives)
        if collectives_by_name_response.get('status') == 'OK':
            collectives_by_name = collectives_by_name_response.get('collectives')
            for collectives in collectives_by_name:
                found_collectives.append(collectives)
        # add found users to list
        if users_by_handle_response.get('status') == 'OK':
            users_by_handle = users_by_handle_response.get('users')
            for users in users_by_handle:
                found_users.append(users)
        if users_by_name_response.get('status') == 'OK':
            users_by_name = users_by_name_response.get('users')
            for users in users_by_name:
                found_users.append(users)
    # if signed in - SHOULD BE IF AUTHENTICTED
    if request.current_user:
        current_user = Auth.get_current_user()
        if not found_users:
            users_response = requests.get(build_url('api/users/3'), data=request.form).json()
            users = users_response.get('users')
        else:
            users = found_users
        if not found_collectives:
            my_collectives = [Collective.get_n_by_cls_and_attr('id', each, 1) for each in current_user.get('collectives')]
        else:
            my_collectives = found_collectives
        data['current_user'] = current_user
        data['full_view'] = request.full_view
        data['collectives'] = my_collectives
        data['users'] = users
    else:
        if not found_users:
            users_response = requests.get(build_url('api/users/3'), data=request.form).json()
            users = users_response.get('users')
        else:
            users = found_users
        if not found_collectives:
            collectives_response = requests.get(build_url('api/collectives/3'), data=request.form).json()
            collectives = collectives_response.get('collectives')
        else:
            collectives = found_collectives
        data['users'] = users
        data['collectives'] = collectives
        data['full_view'] = request.full_view
        print('IN HERE')
    return render_template('/dash/search.html', data=data)


@dash.route('/create_collective', methods=['GET'], strict_slashes=False)
def create_collective():
    """ page with forms for creating a collective """
    from models.users import User
    user = User.get_n_by_cls_and_attr('id', request.current_user, 1)
    data = {
        'current_user': user,
        'full_view': request.full_view
    }
    return render_template('/dash/create_collective.html', data=data)

templates/private/collective.html
{% extends 'dash/dash_base.html' %}

{% block title %}
Collective Name | 
{% endblock %}

<!-- ================================= CONTENT -->
{% block content %}




{% if data.collective %}
{% set collective = data.collective %}


        
<div class="row a-center">
    <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/collective.jpg" id="post-user-pic">
<div class="col">
        <h1 class="page-title" >{{ collective.name }}</h1>
        <h3>@{{ collective.handle }}</h3>
</div>
</div>

<nav class="row" id="sub-nav">

    <div class="sub-nav-item btn-submit" id="props-nav" onclick="showProps()">PROPS</div>
    <div class="sub-nav-item btn-submit" id="tasks-nav" onclick="showTask()">TASKS</div>
    <div class="sub-nav-item btn-submit" id="roles-nav" onclick="showRoles()">ROLES</div>
    <div class="sub-nav-item btn-submit" id="posts-nav">POSTS</div>
    <div class="sub-nav-item btn-submit" id="dues-nav">DUES</div>
    <div class="sub-nav-item btn-submit" id="members-nav">MEMBERS</div>

</nav>



<section class="col-tabs" id="props">


    <div class="card">
        <header>
          <div class="btn btn-lg-dark btn-submit">&#128161;&#xFE0E;  Create Proposal</div>
        </header>
    </div>
    <br>
    <h2>PROPOSALS</h2>

    <div class="card post">

        <header>

          <a href="/me" class="row a-center">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/user.svg" id="post-user-pic">
            <div class="col m-start" >
              <h1>Username</h1>
              <h2>@handle</h2>
            </div>
          </a>

          <div>
              <h3 class="pending">PENDING</h3>
          </div>

        </header>

      <div class="card-body col m-between">

        <div class="prop-description col">
            <h1 class="card-sub-h">Description:</h1>
            Here users can explain why they're proposing what they are.
        </div>
        <hr class="wide">
        <div class="prop-actions col">
            <h1 class="card-sub-h">Actions</h1>
            This is an automated list of exactly what will be enacted if this passes.<br>
        </div>
        <hr class="wide">
        <div class="pass-conditions m-between row wide">
            <div class="col">
                <h2 class="card-sub-h">Pass Conditions</h2>
                <h3>Membership - 50% + 1 </h3>
            </div>
            <div class="col">
                <h2 class="card-sub-h">Status:</h2>
                <h3 class="pending">1/5</h3>
            </div>
            
        </div>
        <hr class="wide">
      
      </div>


      <footer>
      
        <div class="row m-between wide">

            <div class="btn btn-lg-dark wide">Approve</div>
            <div class="btn btn-lg-light wide">Deny</div>

        </div>

      </footer>


    </div>





    <div class="card post">

        <header>

          <a href="/me" class="row a-center">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/russ.jpg" id="post-user-pic">
            <div class="col m-start" >
              <h1>Username</h1>
              <h2>@userhandle</h2>
            </div>
          </a>

          <div>
              <h3 class="approved">APROVED</h3>
          </div>

        </header>

      <div class="card-body col m-between">

        <div class="prop-description col">
            <h1 class="card-sub-h">Description:</h1>
            Here users can explain why they're proposing what they are.
        </div>
        <hr class="wide">
        <div class="prop-actions col">
            <h1 class="card-sub-h">Actions</h1>
            This is an automated list of exactly what will be enacted if this passes.<br>
        </div>
        <hr class="wide">
        <div class="pass-conditions m-between row wide">
            <div class="col">
                <h2 class="card-sub-h">Pass Conditions</h2>
                <h3>Membership - 50% + 1 </h3>
            </div>
            <div class="col">
                <h2 class="card-sub-h">Status:</h2>
                <h3 class="approved">3/5</h3>
            </div>
            
        </div>
        <hr class="wide">
      
      </div>

    </div>



    <div class="card post">

        <header>

          <a href="/me" class="row a-center">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/user.svg" id="post-user-pic">
            <div class="col m-start" >
              <h1>Username</h1>
              <h2>@userhandle</h2>
            </div>
          </a>

          <div>
              <h3 class="denied">DENIED</h3>
          </div>

        </header>

      <div class="card-body col m-between">

        <div class="prop-description col">
            <h1 class="card-sub-h">Description:</h1>
            Here users can explain why they're proposing what they are.
        </div>
        <hr class="wide">
        <div class="prop-actions col">
            <h1 class="card-sub-h">Actions</h1>
            This is an automated list of exactly what will be enacted if this passes.<br>
        </div>
        <hr class="wide">
        <div class="pass-conditions m-between row wide">
            <div class="col">
                <h2 class="card-sub-h">Pass Conditions</h2>
                <h3>Team Lead Approval </h3>
            </div>
            <div class="col">
                <h2 class="card-sub-h">Status:</h2>
                <h3 class="denied">denied</h3>
            </div>
            
        </div>
        <hr class="wide">
      
      </div>

    </div>






</section>











<!-- ================================= TASKS -->

<section id="tasks">

<div class="card">
        <header>
          <div class="btn btn-lg-dark btn-submit"> 📝 Create Task</div>
        </header>
    </div>
    <br>
    <h2>TASKS</h2>

    <div class="card post">

        <header>

          <a href="/me" class="row a-center">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/russ.jpg" id="post-user-pic">
            <div class="col m-start" >
              <h1>Russell Molimock</h1>
              <h2>@rmolimock</h2>
            </div>
          </a>

          <div>
              <h3 class="pending">INCOMPLETE</h3>
          </div>

        </header>

      <div class="card-body col m-between">

        <div class="task-description col">
            <h1 class="card-sub-h">Descrition:</h1>
            For the minimally viable product, users will simply describe the task in a text field. In the future this will become much more fully featured and useful.
        </div>
        <hr class="wide">
        <div class="task-due-date col">
            <h1 class="card-sub-h">Due Date:</h1>
            <h3 class="pending">01-01-2021</h3>
        </div>
        <hr class="who-can-approve wide">
        <div class="col">
            <h1 class="card-sub-h">Who Can Approve:</h1>
            
            <a href="/me" class="row a-center">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/user.svg" id="post-user-pic">
            <div class="col m-start" >
              <h3>Username</h3>
              @userhandle
            </div>
          </a>
          
        </div>
      </div>


      <footer>
      
        <div class="row m-between wide">

            <div class="btn btn-lg-dark wide">Mark Complete</div>

        </div>

      </footer>


    </div>

    




    <div class="card post">

        <header>
            
          <a href="/me" class="row a-center">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/user.svg" id="post-user-pic">
            <div class="col m-start" >
              <h1>Username</h1>
              <h2>@handle</h2>
            </div>
          </a>

          <div>
              <h3 class="approved">SUBMITTED</h3>
          </div>

        </header>

      <div class="card-body col m-between">

        <div class="task-description col">
            <h1 class="card-sub-h">Descrition:</h1>
            Assigner describes the task here... Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sut.
        </div>
        <hr class="wide">
        <div class="task-due-date col">
            <h1 class="card-sub-h">Due Date:</h1>
            <h3 class="pending">01-01-2021</h3>
        </div>
        <hr class="who-can-approve wide">
        <div class="col">
            <h1 class="card-sub-h">Who Can Approve:</h1>
            
            <a href="/me" class="row a-center a-center">
            <img class="profile-pic" src="https://storage.googleapis.com/tpitci-static-images/russ.jpg" id="post-user-pic">
            <div class="col m-start" >
              <h3>Russell Molimock</h3>
              @rmolimock
            </div>
          </a>
          
        </div>
      </div>


      <footer>
      
        <div class="row m-between wide">

            <div class="btn btn-lg-dark wide">Approve</div>
            <div class="btn btn-lg-light wide">Deny</div>

        </div>

      </footer>


    </div>








</section>









<section id="roles">
    Roles Section
</section>












<head>

    <script>
        document.getElementById("props-nav").style.backgroundColor = "var(--color-light)";
        var tasks = document.getElementById("tasks");
        tasks.classList.add("hide");
        var roles = document.getElementById("roles");
        roles.classList.add("hide");

    
        function showTask() {
        var props = document.getElementById("props");
        var tasks = document.getElementById("tasks");
        var roles = document.getElementById("roles");

        document.getElementById("tasks-nav").style.backgroundColor = "var(--color-light)";
        tasks.classList.remove("hide");
        tasks.classList.add("show");

        props.classList.add("hide");
        props.classList.remove("show");
        roles.classList.add("hide");
        roles.classList.remove("show");
        document.getElementById("props-nav").style.backgroundColor = "var(--color-lightest)";
        document.getElementById("roles-nav").style.backgroundColor = "var(--color-lightest)";
        };

        function showProps() {
        var props = document.getElementById("props");
        var tasks = document.getElementById("tasks");
        var roles = document.getElementById("roles");

        tasks.classList.remove("show");
        tasks.classList.add("hide");
        roles.classList.remove("show");
        roles.classList.add("hide");

        document.getElementById("props-nav").style.backgroundColor = "var(--color-light)";
        props.classList.add("show");
        props.classList.remove("hide");

        document.getElementById("tasks-nav").style.backgroundColor = "var(--color-lightest)";
        document.getElementById("roles-nav").style.backgroundColor = "var(--color-lightest)";
        };

        function showRoles() {
        var props = document.getElementById("props");
        var tasks = document.getElementById("tasks");
        var roles = document.getElementById("roles");

        roles.classList.remove("hide");
        roles.classList.add("show");
        document.getElementById("roles-nav").style.backgroundColor = "var(--color-light)";

        props.classList.add("hide");
        props.classList.remove("show");
        tasks.classList.remove("show");
        tasks.classList.add("hide");
        
        document.getElementById("tasks-nav").style.backgroundColor = "var(--color-lightest)";
        document.getElementById("props-nav").style.backgroundColor = "var(--color-lightest)";
        };


    </script>

</head>



{% endif %}

<h1 class="page-title">404 Not found</h1>

{% endblock %}

templates/private/role.html
{% extends 'dash/dash_base.html' %}

{% block title %}
Role | 
{% endblock %}

<!-- ================================= CONTENT -->
{% block content %}

This is role {{id}}

<a href="{{ url_for('collectives.index') }}">back to my collective</a>
<a href="{{ url_for('dash.public_square') }}">Public Square</a>


{% endblock %}